GET http://localhost:8080/api/usuarios/ HTTP/1.1


DELETE  http://localhost:8080/api/usuarios/6280219abea0c4d49258e296 HTTP/1.1




POST  http://localhost:8080/api/usuarios HTTP/1.1
content-type: application/json

{
    "nombre": "mohamed",
    "correo":"mohassa@hotmail.com",
    "password": "Moha90dd",
    "rol" : "ADMIN_ROLE"
}

